# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/demo/Desktop/v4l2rtspserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/demo/Desktop/v4l2rtspserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/demo/Desktop/v4l2rtspserver/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demo/Desktop/v4l2rtspserver/CMakeFiles /home/demo/Desktop/v4l2rtspserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demo/Desktop/v4l2rtspserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named v4l2rtspserver

# Build rule for target.
v4l2rtspserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 v4l2rtspserver
.PHONY : v4l2rtspserver

# fast build rule for target.
v4l2rtspserver/fast:
	$(MAKE) -f CMakeFiles/v4l2rtspserver.dir/build.make CMakeFiles/v4l2rtspserver.dir/build
.PHONY : v4l2rtspserver/fast

#=============================================================================
# Target rules for targets named libv4l2rtspserver

# Build rule for target.
libv4l2rtspserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libv4l2rtspserver
.PHONY : libv4l2rtspserver

# fast build rule for target.
libv4l2rtspserver/fast:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/build
.PHONY : libv4l2rtspserver/fast

#=============================================================================
# Target rules for targets named libv4l2cpp

# Build rule for target.
libv4l2cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libv4l2cpp
.PHONY : libv4l2cpp

# fast build rule for target.
libv4l2cpp/fast:
	$(MAKE) -f libv4l2cpp/CMakeFiles/libv4l2cpp.dir/build.make libv4l2cpp/CMakeFiles/libv4l2cpp.dir/build
.PHONY : libv4l2cpp/fast

#=============================================================================
# Target rules for targets named libv4l2cpptest

# Build rule for target.
libv4l2cpptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libv4l2cpptest
.PHONY : libv4l2cpptest

# fast build rule for target.
libv4l2cpptest/fast:
	$(MAKE) -f libv4l2cpp/CMakeFiles/libv4l2cpptest.dir/build.make libv4l2cpp/CMakeFiles/libv4l2cpptest.dir/build
.PHONY : libv4l2cpptest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/v4l2rtspserver.dir/build.make CMakeFiles/v4l2rtspserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/v4l2rtspserver.dir/build.make CMakeFiles/v4l2rtspserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/v4l2rtspserver.dir/build.make CMakeFiles/v4l2rtspserver.dir/main.cpp.s
.PHONY : main.cpp.s

src/ALSACapture.o: src/ALSACapture.cpp.o

.PHONY : src/ALSACapture.o

# target to build an object file
src/ALSACapture.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ALSACapture.cpp.o
.PHONY : src/ALSACapture.cpp.o

src/ALSACapture.i: src/ALSACapture.cpp.i

.PHONY : src/ALSACapture.i

# target to preprocess a source file
src/ALSACapture.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ALSACapture.cpp.i
.PHONY : src/ALSACapture.cpp.i

src/ALSACapture.s: src/ALSACapture.cpp.s

.PHONY : src/ALSACapture.s

# target to generate assembly for a file
src/ALSACapture.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ALSACapture.cpp.s
.PHONY : src/ALSACapture.cpp.s

src/H264_V4l2DeviceSource.o: src/H264_V4l2DeviceSource.cpp.o

.PHONY : src/H264_V4l2DeviceSource.o

# target to build an object file
src/H264_V4l2DeviceSource.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H264_V4l2DeviceSource.cpp.o
.PHONY : src/H264_V4l2DeviceSource.cpp.o

src/H264_V4l2DeviceSource.i: src/H264_V4l2DeviceSource.cpp.i

.PHONY : src/H264_V4l2DeviceSource.i

# target to preprocess a source file
src/H264_V4l2DeviceSource.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H264_V4l2DeviceSource.cpp.i
.PHONY : src/H264_V4l2DeviceSource.cpp.i

src/H264_V4l2DeviceSource.s: src/H264_V4l2DeviceSource.cpp.s

.PHONY : src/H264_V4l2DeviceSource.s

# target to generate assembly for a file
src/H264_V4l2DeviceSource.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H264_V4l2DeviceSource.cpp.s
.PHONY : src/H264_V4l2DeviceSource.cpp.s

src/H265_V4l2DeviceSource.o: src/H265_V4l2DeviceSource.cpp.o

.PHONY : src/H265_V4l2DeviceSource.o

# target to build an object file
src/H265_V4l2DeviceSource.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H265_V4l2DeviceSource.cpp.o
.PHONY : src/H265_V4l2DeviceSource.cpp.o

src/H265_V4l2DeviceSource.i: src/H265_V4l2DeviceSource.cpp.i

.PHONY : src/H265_V4l2DeviceSource.i

# target to preprocess a source file
src/H265_V4l2DeviceSource.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H265_V4l2DeviceSource.cpp.i
.PHONY : src/H265_V4l2DeviceSource.cpp.i

src/H265_V4l2DeviceSource.s: src/H265_V4l2DeviceSource.cpp.s

.PHONY : src/H265_V4l2DeviceSource.s

# target to generate assembly for a file
src/H265_V4l2DeviceSource.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H265_V4l2DeviceSource.cpp.s
.PHONY : src/H265_V4l2DeviceSource.cpp.s

src/H26x_V4l2DeviceSource.o: src/H26x_V4l2DeviceSource.cpp.o

.PHONY : src/H26x_V4l2DeviceSource.o

# target to build an object file
src/H26x_V4l2DeviceSource.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H26x_V4l2DeviceSource.cpp.o
.PHONY : src/H26x_V4l2DeviceSource.cpp.o

src/H26x_V4l2DeviceSource.i: src/H26x_V4l2DeviceSource.cpp.i

.PHONY : src/H26x_V4l2DeviceSource.i

# target to preprocess a source file
src/H26x_V4l2DeviceSource.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H26x_V4l2DeviceSource.cpp.i
.PHONY : src/H26x_V4l2DeviceSource.cpp.i

src/H26x_V4l2DeviceSource.s: src/H26x_V4l2DeviceSource.cpp.s

.PHONY : src/H26x_V4l2DeviceSource.s

# target to generate assembly for a file
src/H26x_V4l2DeviceSource.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/H26x_V4l2DeviceSource.cpp.s
.PHONY : src/H26x_V4l2DeviceSource.cpp.s

src/HTTPServer.o: src/HTTPServer.cpp.o

.PHONY : src/HTTPServer.o

# target to build an object file
src/HTTPServer.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/HTTPServer.cpp.o
.PHONY : src/HTTPServer.cpp.o

src/HTTPServer.i: src/HTTPServer.cpp.i

.PHONY : src/HTTPServer.i

# target to preprocess a source file
src/HTTPServer.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/HTTPServer.cpp.i
.PHONY : src/HTTPServer.cpp.i

src/HTTPServer.s: src/HTTPServer.cpp.s

.PHONY : src/HTTPServer.s

# target to generate assembly for a file
src/HTTPServer.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/HTTPServer.cpp.s
.PHONY : src/HTTPServer.cpp.s

src/MJPEGVideoSource.o: src/MJPEGVideoSource.cpp.o

.PHONY : src/MJPEGVideoSource.o

# target to build an object file
src/MJPEGVideoSource.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MJPEGVideoSource.cpp.o
.PHONY : src/MJPEGVideoSource.cpp.o

src/MJPEGVideoSource.i: src/MJPEGVideoSource.cpp.i

.PHONY : src/MJPEGVideoSource.i

# target to preprocess a source file
src/MJPEGVideoSource.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MJPEGVideoSource.cpp.i
.PHONY : src/MJPEGVideoSource.cpp.i

src/MJPEGVideoSource.s: src/MJPEGVideoSource.cpp.s

.PHONY : src/MJPEGVideoSource.s

# target to generate assembly for a file
src/MJPEGVideoSource.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MJPEGVideoSource.cpp.s
.PHONY : src/MJPEGVideoSource.cpp.s

src/MemoryBufferSink.o: src/MemoryBufferSink.cpp.o

.PHONY : src/MemoryBufferSink.o

# target to build an object file
src/MemoryBufferSink.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MemoryBufferSink.cpp.o
.PHONY : src/MemoryBufferSink.cpp.o

src/MemoryBufferSink.i: src/MemoryBufferSink.cpp.i

.PHONY : src/MemoryBufferSink.i

# target to preprocess a source file
src/MemoryBufferSink.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MemoryBufferSink.cpp.i
.PHONY : src/MemoryBufferSink.cpp.i

src/MemoryBufferSink.s: src/MemoryBufferSink.cpp.s

.PHONY : src/MemoryBufferSink.s

# target to generate assembly for a file
src/MemoryBufferSink.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MemoryBufferSink.cpp.s
.PHONY : src/MemoryBufferSink.cpp.s

src/MulticastServerMediaSubsession.o: src/MulticastServerMediaSubsession.cpp.o

.PHONY : src/MulticastServerMediaSubsession.o

# target to build an object file
src/MulticastServerMediaSubsession.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MulticastServerMediaSubsession.cpp.o
.PHONY : src/MulticastServerMediaSubsession.cpp.o

src/MulticastServerMediaSubsession.i: src/MulticastServerMediaSubsession.cpp.i

.PHONY : src/MulticastServerMediaSubsession.i

# target to preprocess a source file
src/MulticastServerMediaSubsession.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MulticastServerMediaSubsession.cpp.i
.PHONY : src/MulticastServerMediaSubsession.cpp.i

src/MulticastServerMediaSubsession.s: src/MulticastServerMediaSubsession.cpp.s

.PHONY : src/MulticastServerMediaSubsession.s

# target to generate assembly for a file
src/MulticastServerMediaSubsession.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/MulticastServerMediaSubsession.cpp.s
.PHONY : src/MulticastServerMediaSubsession.cpp.s

src/ServerMediaSubsession.o: src/ServerMediaSubsession.cpp.o

.PHONY : src/ServerMediaSubsession.o

# target to build an object file
src/ServerMediaSubsession.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ServerMediaSubsession.cpp.o
.PHONY : src/ServerMediaSubsession.cpp.o

src/ServerMediaSubsession.i: src/ServerMediaSubsession.cpp.i

.PHONY : src/ServerMediaSubsession.i

# target to preprocess a source file
src/ServerMediaSubsession.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ServerMediaSubsession.cpp.i
.PHONY : src/ServerMediaSubsession.cpp.i

src/ServerMediaSubsession.s: src/ServerMediaSubsession.cpp.s

.PHONY : src/ServerMediaSubsession.s

# target to generate assembly for a file
src/ServerMediaSubsession.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/ServerMediaSubsession.cpp.s
.PHONY : src/ServerMediaSubsession.cpp.s

src/TSServerMediaSubsession.o: src/TSServerMediaSubsession.cpp.o

.PHONY : src/TSServerMediaSubsession.o

# target to build an object file
src/TSServerMediaSubsession.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/TSServerMediaSubsession.cpp.o
.PHONY : src/TSServerMediaSubsession.cpp.o

src/TSServerMediaSubsession.i: src/TSServerMediaSubsession.cpp.i

.PHONY : src/TSServerMediaSubsession.i

# target to preprocess a source file
src/TSServerMediaSubsession.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/TSServerMediaSubsession.cpp.i
.PHONY : src/TSServerMediaSubsession.cpp.i

src/TSServerMediaSubsession.s: src/TSServerMediaSubsession.cpp.s

.PHONY : src/TSServerMediaSubsession.s

# target to generate assembly for a file
src/TSServerMediaSubsession.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/TSServerMediaSubsession.cpp.s
.PHONY : src/TSServerMediaSubsession.cpp.s

src/UnicastServerMediaSubsession.o: src/UnicastServerMediaSubsession.cpp.o

.PHONY : src/UnicastServerMediaSubsession.o

# target to build an object file
src/UnicastServerMediaSubsession.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/UnicastServerMediaSubsession.cpp.o
.PHONY : src/UnicastServerMediaSubsession.cpp.o

src/UnicastServerMediaSubsession.i: src/UnicastServerMediaSubsession.cpp.i

.PHONY : src/UnicastServerMediaSubsession.i

# target to preprocess a source file
src/UnicastServerMediaSubsession.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/UnicastServerMediaSubsession.cpp.i
.PHONY : src/UnicastServerMediaSubsession.cpp.i

src/UnicastServerMediaSubsession.s: src/UnicastServerMediaSubsession.cpp.s

.PHONY : src/UnicastServerMediaSubsession.s

# target to generate assembly for a file
src/UnicastServerMediaSubsession.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/UnicastServerMediaSubsession.cpp.s
.PHONY : src/UnicastServerMediaSubsession.cpp.s

src/V4L2DeviceSource.o: src/V4L2DeviceSource.cpp.o

.PHONY : src/V4L2DeviceSource.o

# target to build an object file
src/V4L2DeviceSource.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4L2DeviceSource.cpp.o
.PHONY : src/V4L2DeviceSource.cpp.o

src/V4L2DeviceSource.i: src/V4L2DeviceSource.cpp.i

.PHONY : src/V4L2DeviceSource.i

# target to preprocess a source file
src/V4L2DeviceSource.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4L2DeviceSource.cpp.i
.PHONY : src/V4L2DeviceSource.cpp.i

src/V4L2DeviceSource.s: src/V4L2DeviceSource.cpp.s

.PHONY : src/V4L2DeviceSource.s

# target to generate assembly for a file
src/V4L2DeviceSource.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4L2DeviceSource.cpp.s
.PHONY : src/V4L2DeviceSource.cpp.s

src/V4l2RTSPServer.o: src/V4l2RTSPServer.cpp.o

.PHONY : src/V4l2RTSPServer.o

# target to build an object file
src/V4l2RTSPServer.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4l2RTSPServer.cpp.o
.PHONY : src/V4l2RTSPServer.cpp.o

src/V4l2RTSPServer.i: src/V4l2RTSPServer.cpp.i

.PHONY : src/V4l2RTSPServer.i

# target to preprocess a source file
src/V4l2RTSPServer.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4l2RTSPServer.cpp.i
.PHONY : src/V4l2RTSPServer.cpp.i

src/V4l2RTSPServer.s: src/V4l2RTSPServer.cpp.s

.PHONY : src/V4l2RTSPServer.s

# target to generate assembly for a file
src/V4l2RTSPServer.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/V4l2RTSPServer.cpp.s
.PHONY : src/V4l2RTSPServer.cpp.s

src/jpeg2.o: src/jpeg2.cpp.o

.PHONY : src/jpeg2.o

# target to build an object file
src/jpeg2.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/jpeg2.cpp.o
.PHONY : src/jpeg2.cpp.o

src/jpeg2.i: src/jpeg2.cpp.i

.PHONY : src/jpeg2.i

# target to preprocess a source file
src/jpeg2.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/jpeg2.cpp.i
.PHONY : src/jpeg2.cpp.i

src/jpeg2.s: src/jpeg2.cpp.s

.PHONY : src/jpeg2.s

# target to generate assembly for a file
src/jpeg2.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/jpeg2.cpp.s
.PHONY : src/jpeg2.cpp.s

src/x264_encoder.o: src/x264_encoder.cpp.o

.PHONY : src/x264_encoder.o

# target to build an object file
src/x264_encoder.cpp.o:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/x264_encoder.cpp.o
.PHONY : src/x264_encoder.cpp.o

src/x264_encoder.i: src/x264_encoder.cpp.i

.PHONY : src/x264_encoder.i

# target to preprocess a source file
src/x264_encoder.cpp.i:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/x264_encoder.cpp.i
.PHONY : src/x264_encoder.cpp.i

src/x264_encoder.s: src/x264_encoder.cpp.s

.PHONY : src/x264_encoder.s

# target to generate assembly for a file
src/x264_encoder.cpp.s:
	$(MAKE) -f CMakeFiles/libv4l2rtspserver.dir/build.make CMakeFiles/libv4l2rtspserver.dir/src/x264_encoder.cpp.s
.PHONY : src/x264_encoder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... v4l2rtspserver"
	@echo "... libv4l2rtspserver"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... install/local"
	@echo "... test"
	@echo "... libv4l2cpp"
	@echo "... libv4l2cpptest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ALSACapture.o"
	@echo "... src/ALSACapture.i"
	@echo "... src/ALSACapture.s"
	@echo "... src/H264_V4l2DeviceSource.o"
	@echo "... src/H264_V4l2DeviceSource.i"
	@echo "... src/H264_V4l2DeviceSource.s"
	@echo "... src/H265_V4l2DeviceSource.o"
	@echo "... src/H265_V4l2DeviceSource.i"
	@echo "... src/H265_V4l2DeviceSource.s"
	@echo "... src/H26x_V4l2DeviceSource.o"
	@echo "... src/H26x_V4l2DeviceSource.i"
	@echo "... src/H26x_V4l2DeviceSource.s"
	@echo "... src/HTTPServer.o"
	@echo "... src/HTTPServer.i"
	@echo "... src/HTTPServer.s"
	@echo "... src/MJPEGVideoSource.o"
	@echo "... src/MJPEGVideoSource.i"
	@echo "... src/MJPEGVideoSource.s"
	@echo "... src/MemoryBufferSink.o"
	@echo "... src/MemoryBufferSink.i"
	@echo "... src/MemoryBufferSink.s"
	@echo "... src/MulticastServerMediaSubsession.o"
	@echo "... src/MulticastServerMediaSubsession.i"
	@echo "... src/MulticastServerMediaSubsession.s"
	@echo "... src/ServerMediaSubsession.o"
	@echo "... src/ServerMediaSubsession.i"
	@echo "... src/ServerMediaSubsession.s"
	@echo "... src/TSServerMediaSubsession.o"
	@echo "... src/TSServerMediaSubsession.i"
	@echo "... src/TSServerMediaSubsession.s"
	@echo "... src/UnicastServerMediaSubsession.o"
	@echo "... src/UnicastServerMediaSubsession.i"
	@echo "... src/UnicastServerMediaSubsession.s"
	@echo "... src/V4L2DeviceSource.o"
	@echo "... src/V4L2DeviceSource.i"
	@echo "... src/V4L2DeviceSource.s"
	@echo "... src/V4l2RTSPServer.o"
	@echo "... src/V4l2RTSPServer.i"
	@echo "... src/V4l2RTSPServer.s"
	@echo "... src/jpeg2.o"
	@echo "... src/jpeg2.i"
	@echo "... src/jpeg2.s"
	@echo "... src/x264_encoder.o"
	@echo "... src/x264_encoder.i"
	@echo "... src/x264_encoder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

